### PR TITLE
Fix get video recorder opts

### LINKED ISSUE #13: getVideoRecorder replaces provided opts with defaults
I was specifying `width` and `height` options when calling `startVideoRecorder` and they were not being honored. After taking a peek at the code, it looks like `getVideoRecorder` is replacing provided options with defaults. I can open a PR for this shortly.

### PR DESCRIPTION
**Pull request by DubHunt**
Fixes #13

### CODE REVIEW

File: src/modules/bbcore.videoRecorder.js [hunk 1]
```diff
@@ -40,18 +40,17 @@ BBCore.prototype.getVideoRecorder = function (opts, onComplete) {
         opts = null;
     }
     var defOpts = {height: 240, width: 320, force_ssl: false, start: null, stop: null, recorded: null};
-    opts = opts || {};
-    jQuery.extend(opts, defOpts);
+    mergedOpts = jQuery.extend(defOpts, opts);
```
Comment (DubHunt) [inline src/modules/bbcore.videoRecorder.js:43]: No longer mutating the provided `opts` object. `$.extend()` called when `opts` is `undefined` should be safe.

File: spec/BBCoreSpec.js [hunk 2]
```diff
@@ -867,8 +867,10 @@ describe("BBCore.videoRecorder", function() {
         setupMockApiRequest(result.withOptionsSuccess);
 
         bbCore.getVideoRecorder(opts, successCallbackSpy);
-
-        expect($.ajax.calls.argsFor(0)[0].data).toEqual(opts);
```
Comment (DubHunt) [inline spec/BBCoreSpec.js:871]: The reason this test was passing before and hiding the bug is because inside of `getVideoRecorder` `$.extend()` was mutating `opts`.

File: spec/BBCoreSpec.js [hunk 3]
```diff
@@ -867,8 +867,10 @@ describe("BBCore.videoRecorder", function() {
...
+        data = $.ajax.calls.argsFor(0)[0].data
+        for (var k in opts) {
+          expect(data[k]).toEqual(opts[k]);
```
Comment (DubHunt) [inline spec/BBCoreSpec.js:872]: Iterating through keys because comparing objects via `toEqual` won't work as `getVideoRecorder` sticks `method` in the opts. Didn't see a built-in matcher to do this in Jasmine.

**Comment by perl5punk** [comment]
Sorry for not getting this sooner.  Thanks for the updates!
